/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guiaDynamoBasic: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'autogenerated', 
      dirName: '01-DynamoBasics'
    },
    {
      type: 'html',
      value: '<hr/>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'doc',
      id: '01About',
    },
  ],
  guiaDynamoAvanzado: [
    {
      type: 'autogenerated', 
      dirName: '02-DynamoPython'
    },
    {
      type: 'html',
      value: '<hr/>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'doc',
      id: '01About',
    },
  ],
  guiaWPF: [
    {
      type: 'autogenerated', 
      dirName: '03-WPF'
    },
    {
      type: 'html',
      value: '<hr/>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'doc',
      id: '01About',
    },
  ],
  // But you can create a sidebar manually
  
/*
  tutorialSidebar: 
  [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: '01About',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: [
        {
          type: 'doc',
          id: 'Generalidades/01python',
        },
        {
          type: 'doc',
          id: 'Generalidades/02NodoPythonScript',
        },
      ],
    },
    {
      type: 'link',
      label: 'Learn more',
      href: 'https://example.com',
    },
  ],*/
  
   
};



export default sidebars;
